# Generated by Django 4.0.1 on 2022-05-11 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('supporters_needed', models.IntegerField(null=True)),
                ('time_frame', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=1000, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('contact_info', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NeedCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='need.categories')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='need.need')),
            ],
        ),
    ]
