# Generated by Django 4.0.1 on 2022-05-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=2000, null=True)),
                ('phone_text', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
