# Generated by Django 4.0.1 on 2022-06-29 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('need', '0002_supporters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporters',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SupportersCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='need.categories')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='need.supporters')),
            ],
        ),
    ]
