# Generated by Django 4.0.1 on 2022-01-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0002_alter_need_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='supporters_needed',
            field=models.IntegerField(null=True),
        ),
    ]
