# Generated by Django 4.0.1 on 2022-02-12 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0004_categories_needcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='city',
        ),
        migrations.RemoveField(
            model_name='need',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='need',
            name='state',
        ),
        migrations.RemoveField(
            model_name='need',
            name='zip_code',
        ),
    ]
