# Generated by Django 4.0.1 on 2022-03-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0005_remove_need_city_remove_need_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='need',
            old_name='start_time',
            new_name='time_frame',
        ),
        migrations.AddField(
            model_name='need',
            name='adress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='need',
            name='contact_info',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='need',
            name='notes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='need',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
