# Generated by Django 4.0.1 on 2022-03-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('needs', '0006_rename_start_time_need_time_frame_need_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='need',
            old_name='adress',
            new_name='location',
        ),
    ]
